### ISSUE TITLE
Support for low frequencies

### ISSUE THREAD

**Issue by zplizzi** [luni64/TeensyDelay#5] opened 2018-03-28 20:53 UTC
I'm unable to get frequencies lower than about 30Hz (timer periods of 30ms) from this library on a Teensy 3.6. I suspect this is because the timer frequency is set to about 1us (as noted in the config file), and the timers used are 16 bit, which corresponds to at most 65ms or so until the 16 bit timer overflows. 

I looked into changing the prescaler, but with the FTM timers even the highest prescaler only brings it down to about 5Hz. I suspect the TPM timers would go lower, given their lower base clock, but I unfortunately also need 5 independent channels. I was shooting for a minimum of 1Hz for the project I'm working on (but a max of several kHz).

I'm not sure that this is something that can or should be fixed, but it might be worth making a note on the Readme as I suspect many like me wouldn't have expected this behavior.

**Comment by luni64** [comment] 2018-03-30 09:44
As you analyzed correctly the maximum delay time is limited by the 16 bit timer. I'll add a remark to the readme. It is however quite easy to prolong the delay time by something like this:

```c++
void callback(){
    static int cnt = 0;
    if (cnt < 200){                    // ignore 200 trigger events (5s = 200 x 25ms)
        cnt++;
        TeensyDelay::trigger(25000);   // retrigger the timer (25ms)
    }
    else{                              // do whatever needs to be done after 5s
        cnt = 0;                                      
        digitalWriteFast(LED_BUILTIN, LOW);
    }
}

void setup(){
    pinMode(LED_BUILTIN, OUTPUT);

    TeensyDelay::begin();                
    TeensyDelay::addDelayChannel(callback);

    digitalWriteFast(LED_BUILTIN, HIGH);
    TeensyDelay::trigger(1);           // this will switch off the LED after 5s;         
}

void  loop(){    
}
```
The additional processor load caused by retriggering every 25ms is in the order of 1µs / 25000µs = 0.004% and should be negligible for most cases.

I also merged in a few bugfixes and a possibility to override the prescaler in config.h

Hope that helps.

**Comment by zplizzi** [comment] 2018-03-30 23:11
Awesome, thanks so much!

**Closed as completed** 2018-03-31 07:13 UTC
